# Batch Structured JSON Comparison

This notebook compares the `structured_json` outputs under `D:\\AQUMON\\test_batch_size\\batch4` and `D:\\AQUMON\\test_batch_size\\batch8`.

It reports:
- how many JSON files are shared or missing across the two runs
- how many files contain any field-level difference
- how many total field mismatch instances exist across all matched files
- which field paths differ most often
- detailed differences for selected files

In [1]:
from __future__ import annotations

import json
from collections import Counter
from pathlib import Path

import pandas as pd
from IPython.display import display

BATCH4_BASE = Path(r"D:\AQUMON\test_batch_size\batch4")
BATCH8_BASE = Path(r"D:\AQUMON\test_batch_size\batch8")

pd.set_option("display.max_colwidth", 200)
pd.set_option("display.max_rows", 200)

In [2]:
MISSING = object()


def resolve_structured_json_root(base_dir: Path) -> Path:
    direct_root = base_dir / "structured_json"
    if direct_root.exists():
        return direct_root

    candidates = sorted(
        child / "structured_json"
        for child in base_dir.iterdir()
        if child.is_dir() and (child / "structured_json").exists()
    )

    if not candidates:
        raise FileNotFoundError(f"No structured_json directory found under {base_dir}")
    if len(candidates) > 1:
        raise ValueError(
            f"Multiple structured_json directories found under {base_dir}: {candidates}"
        )
    return candidates[0]


def collect_json_files(root: Path) -> dict[str, Path]:
    return {
        str(path.relative_to(root)).replace("\\", "/"): path
        for path in sorted(root.rglob("*.json"))
    }


def flatten_json(value, prefix: str = "") -> dict[str, object]:
    flat: dict[str, object] = {}

    if isinstance(value, dict):
        if prefix and not value:
            flat[prefix] = {}
        for key in sorted(value):
            next_prefix = f"{prefix}.{key}" if prefix else key
            flat.update(flatten_json(value[key], next_prefix))
        return flat

    if isinstance(value, list):
        length_key = f"{prefix}.__len__" if prefix else "__len__"
        flat[length_key] = len(value)
        for idx, item in enumerate(value):
            next_prefix = f"{prefix}[{idx}]" if prefix else f"[{idx}]"
            flat.update(flatten_json(item, next_prefix))
        return flat

    flat[prefix or "$"] = value
    return flat


def display_value(value: object) -> object:
    if value is MISSING:
        return "<MISSING>"
    if isinstance(value, (dict, list)):
        return json.dumps(value, ensure_ascii=False, sort_keys=True)
    return value


def compare_json_objects(left_obj: object, right_obj: object) -> list[dict[str, object]]:
    left_flat = flatten_json(left_obj)
    right_flat = flatten_json(right_obj)
    all_paths = sorted(set(left_flat) | set(right_flat))

    diffs: list[dict[str, object]] = []
    for field_path in all_paths:
        left_value = left_flat.get(field_path, MISSING)
        right_value = right_flat.get(field_path, MISSING)
        if left_value != right_value:
            diffs.append(
                {
                    "field_path": field_path,
                    "batch4_value": display_value(left_value),
                    "batch8_value": display_value(right_value),
                }
            )
    return diffs


def load_json(path: Path) -> object:
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)

In [3]:
batch4_root = resolve_structured_json_root(BATCH4_BASE)
batch8_root = resolve_structured_json_root(BATCH8_BASE)

batch4_files = collect_json_files(batch4_root)
batch8_files = collect_json_files(batch8_root)

common_files = sorted(set(batch4_files) & set(batch8_files))
only_in_batch4 = sorted(set(batch4_files) - set(batch8_files))
only_in_batch8 = sorted(set(batch8_files) - set(batch4_files))

per_file_rows = []
field_counter = Counter()
field_example_rows = {}
diff_details_by_file = {}

for file_key in common_files:
    left_obj = load_json(batch4_files[file_key])
    right_obj = load_json(batch8_files[file_key])
    diffs = compare_json_objects(left_obj, right_obj)

    if diffs:
        diff_details_by_file[file_key] = pd.DataFrame(diffs)

    per_file_rows.append(
        {
            "file_key": file_key,
            "field_mismatch_count": len(diffs),
            "has_difference": bool(diffs),
        }
    )

    for diff in diffs:
        field_path = diff["field_path"]
        field_counter[field_path] += 1
        field_example_rows.setdefault(
            field_path,
            {
                "example_file": file_key,
                "example_batch4_value": diff["batch4_value"],
                "example_batch8_value": diff["batch8_value"],
            },
        )

file_diff_df = pd.DataFrame(per_file_rows).sort_values(
    ["field_mismatch_count", "file_key"],
    ascending=[False, True],
).reset_index(drop=True)

field_diff_df = pd.DataFrame(
    [
        {
            "field_path": field_path,
            "files_with_difference": count,
            **field_example_rows[field_path],
        }
        for field_path, count in field_counter.most_common()
    ]
)

summary_df = pd.DataFrame(
    [
        {
            "batch4_root": str(batch4_root),
            "batch8_root": str(batch8_root),
            "batch4_json_files": len(batch4_files),
            "batch8_json_files": len(batch8_files),
            "common_json_files": len(common_files),
            "only_in_batch4": len(only_in_batch4),
            "only_in_batch8": len(only_in_batch8),
            "files_with_any_difference": int(file_diff_df["has_difference"].sum()),
            "total_field_mismatch_instances": int(file_diff_df["field_mismatch_count"].sum()),
            "unique_field_paths_with_differences": len(field_counter),
        }
    ]
)

display(summary_df)

,batch4_root,batch8_root,batch4_json_files,batch8_json_files,common_json_files,only_in_batch4,only_in_batch8,files_with_any_difference,total_field_mismatch_instances,unique_field_paths_with_differences
0,D:\AQUMON\test_batch_size\batch4\4_extraction_v1_gemi_batch\structured_json,D:\AQUMON\test_batch_size\batch8\4_extraction_v1_gemi_batch\structured_json,54,54,54,0,0,54,310,100

In [4]:
display(file_diff_df)

if only_in_batch4:
    display(pd.DataFrame({"only_in_batch4": only_in_batch4}))

if only_in_batch8:
    display(pd.DataFrame({"only_in_batch8": only_in_batch8}))

,file_key,field_mismatch_count,has_difference
0,TDG/0000919574-20-002399/0000919574-20-002399.json,32,True
1,SPGI/0000064040-23-000067/0000064040-23-000067.json,20,True
2,YOU/0001209191-22-028778/0001209191-22-028778.json,16,True
3,INCY/0001209191-20-025112/0001209191-20-025112.json,15,True
4,KALU/0001209191-22-045612/0001209191-22-045612.json,13,True
5,PSX/0001534701-20-000072/0001534701-20-000072.json,13,True
6,IRM/0001020569-22-000056/0001020569-22-000056.json,12,True
7,KR/0001209191-20-019112/0001209191-20-019112.json,12,True
8,LOVE/0001213900-24-034233/0001213900-24-034233.json,12,True
9,COF/0000927628-21-000067/0000927628-21-000067.json,10,True
10,KR/0001209191-20-017945/0001209191-20-017945.json,9,True
11,SYNA/0001209191-20-021443/0001209191-20-021443.json,9,True
12,AGO/0001209191-20-021889/0001209191-20-021889.json,7,True
13,LOB/0001209191-20-018455/0001209191-20-018455.json,7,True
14,NXST/0001209191-20-019874/0001209191-20-019874.json,7,True
15,CWH/0001104659-20-030766/0001104659-20-030766.json,6,True
16,WW/0001209191-20-022112/0001209191-20-022112.json,6,True
17,CFR/0001209191-20-016737/0001209191-20-016737.json,5,True
18,GNW/0001209191-20-022145/0001209191-20-022145.json,5,True
19,PSN/0000899243-20-008213/0000899243-20-008213.json,5,True
20,ARW/0001127602-20-010778/0001127602-20-010778.json,4,True
21,BKR/0001701605-18-000067/0001701605-18-000067.json,4,True
22,KMI/0001506307-20-000089/0001506307-20-000089.json,4,True
23,NXST/0001209191-20-020667/0001209191-20-020667.json,4,True
24,THRM/0001209191-20-023778/0001209191-20-023778.json,4,True
25,TLYS/0001209191-20-020278/0001209191-20-020278.json,4,True
26,TRC/0001209191-20-024112/0001209191-20-024112.json,4,True
27,VTR/0000740260-22-000089/0000740260-22-000089.json,4,True
28,ADSK/0001209191-20-021012/0001209191-20-021012.json,3,True
29,AMD/0000002488-18-000045/0000002488-18-000045.json,3,True
30,CVLT/0001209191-18-061223/0001209191-18-061223.json,3,True
31,EQH/0001209191-20-017245/0001209191-20-017245.json,3,True
32,HLX/0001209191-20-022554/0001209191-20-022554.json,3,True
33,INTC/0001127602-21-027635/0001127602-21-027635.json,3,True
34,KDP/0001209191-20-018902/0001209191-20-018902.json,3,True
35,LII/0001127602-20-011102/0001127602-20-011102.json,3,True
36,PSN/0000899243-20-008612/0000899243-20-008612.json,3,True
37,SNAP/0001209191-20-020112/0001209191-20-020112.json,3,True
38,TRIP/0001127602-20-009718/0001127602-20-009718.json,3,True
39,CACC/0000885550-20-000030/0000885550-20-000030.json,2,True
40,CAT/0000018230-19-000102/0000018230-19-000102.json,2,True
41,CBT/0001209191-22-040221/0001209191-22-040221.json,2,True
42,FBP/0001209191-20-020889/0001209191-20-020889.json,2,True
43,IDCC/0001209191-20-025667/0001209191-20-025667.json,2,True
44,NBIX/0001209191-22-030998/0001209191-22-030998.json,2,True
45,PSN/0000899243-20-008522/0000899243-20-008522.json,2,True
46,UPBD/0000933036-21-000014/0000933036-21-000014.json,2,True
47,UPBD/0000933036-21-000095/0000933036-21-000095.json,2,True
48,CFG/0000759944-20-000054/0000759944-20-000054.json,1,True
49,HESM/0001209191-20-015600/0001209191-20-015600.json,1,True
50,HOOD/0001783879-22-000098/0001783879-22-000098.json,1,True
51,VICI/0001705696-20-000072/0001705696-20-000072.json,1,True
52,VYX/0001209191-20-025445/0001209191-20-025445.json,1,True
53,WES/0001127602-20-009648/0001127602-20-009648.json,1,True

In [5]:
display(field_diff_df)

,field_path,files_with_difference,example_file,example_batch4_value,example_batch8_value
0,filing_date,36,ADSK/0001209191-20-021012/0001209191-20-021012.json,2020-03-24,None
1,table_i_non_derivative[0].transaction_form_type_indicator_v,20,ADSK/0001209191-20-021012/0001209191-20-021012.json,False,None
2,table_i_non_derivative[1].transaction_form_type_indicator_v,12,ADSK/0001209191-20-021012/0001209191-20-021012.json,False,None
3,remarks,11,AGO/0001209191-20-021889/0001209191-20-021889.json,"/s/ Ling Chow, Attorney-in-fact",None
4,table_i_non_derivative[2].transaction_form_type_indicator_v,8,AGO/0001209191-20-021889/0001209191-20-021889.json,False,None
5,period_of_report,8,BKR/0001701605-18-000067/0001701605-18-000067.json,None,2018-05-11
6,filing_characteristics.rule_10b5_1,8,CFG/0000759944-20-000054/0000759944-20-000054.json,None,False
7,date_of_earliest_transaction,8,INCY/0001209191-20-025112/0001209191-20-025112.json,04/16/2020,2020-04-16
8,table_i_non_derivative[0].transaction_date,8,INCY/0001209191-20-025112/0001209191-20-025112.json,04/16/2020,2020-04-16
9,table_i_non_derivative[0].transaction_code_footnote_refs.__len__,7,ARW/0001127602-20-010778/0001127602-20-010778.json,1,0
10,table_i_non_derivative[0].transaction_code_footnote_refs[0],7,ARW/0001127602-20-010778/0001127602-20-010778.json,1,<MISSING>
11,table_ii_derivative[0].date_exercisable,7,COF/0000927628-21-000067/0000927628-21-000067.json,(5),None
12,table_ii_derivative[0].expiration_date,7,COF/0000927628-21-000067/0000927628-21-000067.json,(5),None
13,table_i_non_derivative[0].price_footnote_refs.__len__,7,IRM/0001020569-22-000056/0001020569-22-000056.json,1,0
14,table_i_non_derivative[3].transaction_form_type_indicator_v,6,AGO/0001209191-20-021889/0001209191-20-021889.json,False,None
15,table_i_non_derivative[1].shares_owned_following_transaction,6,CFR/0001209191-20-016737/0001209191-20-016737.json,4500,None
16,table_i_non_derivative[1].transaction_shares,6,CFR/0001209191-20-016737/0001209191-20-016737.json,None,4500
17,table_i_non_derivative[0].price_footnote_refs[0],6,IRM/0001020569-22-000056/0001020569-22-000056.json,1,<MISSING>
18,table_ii_derivative[0].transaction_acquired_disposed_code,5,COF/0000927628-21-000067/0000927628-21-000067.json,A,None
19,table_ii_derivative[0].transaction_form_type_indicator_v,5,KDP/0001209191-20-018902/0001209191-20-018902.json,False,None
20,table_i_non_derivative[4].transaction_form_type_indicator_v,4,AGO/0001209191-20-021889/0001209191-20-021889.json,False,None
21,table_ii_derivative[0].conversion_or_exercise_price,4,GNW/0001209191-20-022145/0001209191-20-022145.json,(1),None
22,footnotes[0].text,4,HLX/0001209191-20-022554/0001209191-20-022554.json,"This restricted stock award was granted pursuant to the Company's 2005 Long Term Incentive Plan (as Amended and Restated effective May 15, 2019) and therefore has no purchase or sales price. This ...","This restricted stock award was granted pursuant to the Company's 2005 Long Term Incentive Plan (as Amended and Restated effective May 15, 2019) and therefore has no purchase or sales price.\nThis..."
23,table_i_non_derivative[1].transaction_date,4,INCY/0001209191-20-025112/0001209191-20-025112.json,04/16/2020,2020-04-16
24,table_i_non_derivative[2].transaction_shares,3,CFR/0001209191-20-016737/0001209191-20-016737.json,None,5000
25,table_i_non_derivative[1].nature_of_ownership,3,CWH/0001104659-20-030766/0001104659-20-030766.json,See footnote (2),See footnote
26,table_ii_derivative[0].transaction_date,3,INCY/0001209191-20-025112/0001209191-20-025112.json,04/16/2020,2020-04-16
27,table_ii_derivative[1].expiration_date,3,INCY/0001209191-20-025112/0001209191-20-025112.json,01/03/2029,2029-01-03
28,table_ii_derivative[1].transaction_acquired_disposed_code,3,INCY/0001209191-20-025112/0001209191-20-025112.json,None,A
29,table_i_non_derivative[1].price_footnote_refs.__len__,3,KALU/0001209191-22-045612/0001209191-22-045612.json,1,0
30,table_i_non_derivative[1].price_footnote_refs[0],3,KALU/0001209191-22-045612/0001209191-22-045612.json,2,<MISSING>
31,table_ii_derivative[0].transaction_code_footnote_refs.__len__,2,BKR/0001701605-18-000067/0001701605-18-000067.json,0,1
32,table_ii_derivative[0].transaction_code_footnote_refs[0],2,BKR/0001701605-18-000067/0001701605-18-000067.json,<MISSING>,1
33,table_i_non_derivative[2].shares_owned_following_transaction,2,CFR/0001209191-20-016737/0001209191-20-016737.json,5000,None
34,table_i_non_derivative[5].transaction_shares,2,COF/0000927628-21-000067/0000927628-21-000067.json,None,15
35,table_i_non_derivative[6].transaction_shares,2,COF/0000927628-21-000067/0000927628-21-000067.json,None,17743
36,footnotes[1].text,2,CWH/0001104659-20-030766/0001104659-20-030766.json,"The securities reported herein are held of record by ML Acquisition Company, LLC. CWGS Holding, LLC is a wholly owned subsidiary of ML Acquisition Company, LLC. Marcus Lemonis, as the sole directo...","The securities reported herein are held of record by ML Acquisition Company, LLC.\nCWGS Holding, LLC is a wholly owned subsidiary of ML Acquisition Company, LLC. Marcus Lemonis, as the sole direct..."
37,reporting_person.relationship_to_issuer.officer_title,2,EQH/0001209191-20-017245/0001209191-20-017245.json,"Senior Executive Vice President and Head of Retirement, Wealth Management & Protection Solutions",(See Remarks)
38,table_i_non_derivative[2].transaction_date,2,INCY/0001209191-20-025112/0001209191-20-025112.json,04/17/2020,2020-04-17
39,table_i_non_derivative[3].transaction_date,2,INCY/0001209191-20-025112/0001209191-20-025112.json,04/17/2020,2020-04-17
40,table_ii_derivative[1].transaction_date,2,INCY/0001209191-20-025112/0001209191-20-025112.json,04/17/2020,2020-04-17
41,table_ii_derivative[1].transaction_form_type_indicator_v,2,KR/0001209191-20-017945/0001209191-20-017945.json,False,None
42,table_i_non_derivative[5].transaction_form_type_indicator_v,2,LOVE/0001213900-24-034233/0001213900-24-034233.json,False,None
43,table_ii_derivative[1].conversion_or_exercise_price,2,NXST/0001209191-20-019874/0001209191-20-019874.json,(1),None
44,table_ii_derivative[1].date_exercisable,2,NXST/0001209191-20-019874/0001209191-20-019874.json,(3),None
45,table_i_non_derivative[2].price_footnote_refs.__len__,2,PSX/0001534701-20-000072/0001534701-20-000072.json,1,0
46,table_i_non_derivative[2].price_footnote_refs[0],2,PSX/0001534701-20-000072/0001534701-20-000072.json,1,<MISSING>
47,table_i_non_derivative[5].shares_owned_following_transaction,1,COF/0000927628-21-000067/0000927628-21-000067.json,15,None
48,table_i_non_derivative[6].shares_owned_following_transaction,1,COF/0000927628-21-000067/0000927628-21-000067.json,17743,None
49,footnotes[4].text,1,CVLT/0001209191-18-061223/0001209191-18-061223.json,"The options to purchase common stock are subject to a 4-year vesting schedule, as follows: 25% on the first anniversary of the grant with the remaining options vesting in equal quarterly installme...","The options to purchase common stock are subject to a 4-year vesting schedule, as follows:\n25% on the first anniversary of the grant with the remaining options vesting in equal quarterly installm..."
50,table_i_non_derivative[3].nature_of_ownership,1,INCY/0001209191-20-025112/0001209191-20-025112.json,None,4
51,table_i_non_derivative[2].transaction_code_footnote_refs.__len__,1,KR/0001209191-20-019112/0001209191-20-019112.json,0,1
52,table_i_non_derivative[2].transaction_code_footnote_refs[0],1,KR/0001209191-20-019112/0001209191-20-019112.json,<MISSING>,2
53,table_i_non_derivative[3].transaction_code_footnote_refs.__len__,1,KR/0001209191-20-019112/0001209191-20-019112.json,0,1
54,table_i_non_derivative[3].transaction_code_footnote_refs[0],1,KR/0001209191-20-019112/0001209191-20-019112.json,<MISSING>,3
55,table_i_non_derivative[6].transaction_form_type_indicator_v,1,LOVE/0001213900-24-034233/0001213900-24-034233.json,False,None
56,table_i_non_derivative[7].transaction_form_type_indicator_v,1,LOVE/0001213900-24-034233/0001213900-24-034233.json,False,None
57,table_i_non_derivative[7].transaction_shares,1,LOVE/0001213900-24-034233/0001213900-24-034233.json,1749,None
58,table_i_non_derivative[4].shares_owned_following_transaction,1,PSN/0000899243-20-008522/0000899243-20-008522.json,85854,None
59,table_i_non_derivative[4].transaction_shares,1,PSN/0000899243-20-008522/0000899243-20-008522.json,None,85854
60,table_i_non_derivative[0].nature_of_ownership,1,PSX/0001534701-20-000072/0001534701-20-000072.json,None,(1)
61,table_i_non_derivative[2].nature_of_ownership,1,PSX/0001534701-20-000072/0001534701-20-000072.json,None,(1)
62,table_ii_derivative[0].derivative_shares,1,SPGI/0000064040-23-000067/0000064040-23-000067.json,1030,None
63,table_ii_derivative[0].transaction_price,1,SPGI/0000064040-23-000067/0000064040-23-000067.json,0.0,None
64,table_ii_derivative[1].derivative_shares,1,SPGI/0000064040-23-000067/0000064040-23-000067.json,367,None
65,table_ii_derivative[1].transaction_price,1,SPGI/0000064040-23-000067/0000064040-23-000067.json,0.0,None
66,table_ii_derivative[2].conversion_or_exercise_price,1,SPGI/0000064040-23-000067/0000064040-23-000067.json,(6),0.0
67,table_ii_derivative[2].derivative_shares,1,SPGI/0000064040-23-000067/0000064040-23-000067.json,4661,None
68,table_ii_derivative[2].transaction_price,1,SPGI/0000064040-23-000067/0000064040-23-000067.json,0.0,None
69,table_i_non_derivative[10].transaction_date,1,TDG/0000919574-20-002399/0000919574-20-002399.json,03/11/2020,2020-03-11
70,table_i_non_derivative[11].transaction_date,1,TDG/0000919574-20-002399/0000919574-20-002399.json,03/11/2020,2020-03-11
71,table_i_non_derivative[12].transaction_date,1,TDG/0000919574-20-002399/0000919574-20-002399.json,03/11/2020,2020-03-11
72,table_i_non_derivative[13].transaction_date,1,TDG/0000919574-20-002399/0000919574-20-002399.json,03/11/2020,2020-03-11
73,table_i_non_derivative[14].transaction_date,1,TDG/0000919574-20-002399/0000919574-20-002399.json,03/11/2020,2020-03-11
74,table_i_non_derivative[15].transaction_date,1,TDG/0000919574-20-002399/0000919574-20-002399.json,03/11/2020,2020-03-11
75,table_i_non_derivative[16].transaction_date,1,TDG/0000919574-20-002399/0000919574-20-002399.json,03/11/2020,2020-03-11
76,table_i_non_derivative[17].transaction_date,1,TDG/0000919574-20-002399/0000919574-20-002399.json,03/11/2020,2020-03-11
77,table_i_non_derivative[18].transaction_date,1,TDG/0000919574-20-002399/0000919574-20-002399.json,03/11/2020,2020-03-11
78,table_i_non_derivative[19].transaction_date,1,TDG/0000919574-20-002399/0000919574-20-002399.json,03/11/2020,2020-03-11
79,table_i_non_derivative[20].transaction_date,1,TDG/0000919574-20-002399/0000919574-20-002399.json,03/11/2020,2020-03-11
80,table_i_non_derivative[21].transaction_date,1,TDG/0000919574-20-002399/0000919574-20-002399.json,03/11/2020,2020-03-11
81,table_i_non_derivative[22].transaction_date,1,TDG/0000919574-20-002399/0000919574-20-002399.json,03/11/2020,2020-03-11
82,table_i_non_derivative[23].transaction_date,1,TDG/0000919574-20-002399/0000919574-20-002399.json,03/11/2020,2020-03-11
83,table_i_non_derivative[24].transaction_date,1,TDG/0000919574-20-002399/0000919574-20-002399.json,03/11/2020,2020-03-11
84,table_i_non_derivative[25].transaction_date,1,TDG/0000919574-20-002399/0000919574-20-002399.json,03/11/2020,2020-03-11
85,table_i_non_derivative[26].transaction_date,1,TDG/0000919574-20-002399/0000919574-20-002399.json,03/11/2020,2020-03-11
86,table_i_non_derivative[27].shares_owned_following_transaction,1,TDG/0000919574-20-002399/0000919574-20-002399.json,20301,None
87,table_i_non_derivative[28].shares_owned_following_transaction,1,TDG/0000919574-20-002399/0000919574-20-002399.json,16765,None
88,table_i_non_derivative[29].shares_owned_following_transaction,1,TDG/0000919574-20-002399/0000919574-20-002399.json,58683,None
89,table_i_non_derivative[4].transaction_date,1,TDG/0000919574-20-002399/0000919574-20-002399.json,03/11/2020,2020-03-11
90,table_i_non_derivative[5].transaction_date,1,TDG/0000919574-20-002399/0000919574-20-002399.json,03/11/2020,2020-03-11
91,table_i_non_derivative[6].transaction_date,1,TDG/0000919574-20-002399/0000919574-20-002399.json,03/11/2020,2020-03-11
92,table_i_non_derivative[7].transaction_date,1,TDG/0000919574-20-002399/0000919574-20-002399.json,03/11/2020,2020-03-11
93,table_i_non_derivative[8].transaction_date,1,TDG/0000919574-20-002399/0000919574-20-002399.json,03/11/2020,2020-03-11
94,table_i_non_derivative[9].transaction_date,1,TDG/0000919574-20-002399/0000919574-20-002399.json,03/11/2020,2020-03-11
95,table_i_non_derivative[0].price_footnote_refs[1],1,TRC/0001209191-20-024112/0001209191-20-024112.json,2,<MISSING>
96,table_i_non_derivative[3].price_footnote_refs.__len__,1,YOU/0001209191-22-028778/0001209191-22-028778.json,1,0
97,table_i_non_derivative[3].price_footnote_refs[0],1,YOU/0001209191-22-028778/0001209191-22-028778.json,1,<MISSING>
98,table_i_non_derivative[4].price_footnote_refs.__len__,1,YOU/0001209191-22-028778/0001209191-22-028778.json,1,0
99,table_i_non_derivative[4].price_footnote_refs[0],1,YOU/0001209191-22-028778/0001209191-22-028778.json,1,<MISSING>

In [6]:
def show_file_differences(file_key: str, max_rows: int = 200) -> pd.DataFrame:
    if file_key not in diff_details_by_file:
        raise KeyError(f"No differences recorded for {file_key}")
    return diff_details_by_file[file_key].head(max_rows)


differing_files = file_diff_df[file_diff_df["field_mismatch_count"] > 0].copy()
display(differing_files)

if not differing_files.empty:
    example_file_key = differing_files.iloc[0]["file_key"]
    print(f"Example file with differences: {example_file_key}")
    display(show_file_differences(example_file_key))

,file_key,field_mismatch_count,has_difference
0,TDG/0000919574-20-002399/0000919574-20-002399.json,32,True
1,SPGI/0000064040-23-000067/0000064040-23-000067.json,20,True
2,YOU/0001209191-22-028778/0001209191-22-028778.json,16,True
3,INCY/0001209191-20-025112/0001209191-20-025112.json,15,True
4,KALU/0001209191-22-045612/0001209191-22-045612.json,13,True
5,PSX/0001534701-20-000072/0001534701-20-000072.json,13,True
6,IRM/0001020569-22-000056/0001020569-22-000056.json,12,True
7,KR/0001209191-20-019112/0001209191-20-019112.json,12,True
8,LOVE/0001213900-24-034233/0001213900-24-034233.json,12,True
9,COF/0000927628-21-000067/0000927628-21-000067.json,10,True
10,KR/0001209191-20-017945/0001209191-20-017945.json,9,True
11,SYNA/0001209191-20-021443/0001209191-20-021443.json,9,True
12,AGO/0001209191-20-021889/0001209191-20-021889.json,7,True
13,LOB/0001209191-20-018455/0001209191-20-018455.json,7,True
14,NXST/0001209191-20-019874/0001209191-20-019874.json,7,True
15,CWH/0001104659-20-030766/0001104659-20-030766.json,6,True
16,WW/0001209191-20-022112/0001209191-20-022112.json,6,True
17,CFR/0001209191-20-016737/0001209191-20-016737.json,5,True
18,GNW/0001209191-20-022145/0001209191-20-022145.json,5,True
19,PSN/0000899243-20-008213/0000899243-20-008213.json,5,True
20,ARW/0001127602-20-010778/0001127602-20-010778.json,4,True
21,BKR/0001701605-18-000067/0001701605-18-000067.json,4,True
22,KMI/0001506307-20-000089/0001506307-20-000089.json,4,True
23,NXST/0001209191-20-020667/0001209191-20-020667.json,4,True
24,THRM/0001209191-20-023778/0001209191-20-023778.json,4,True
25,TLYS/0001209191-20-020278/0001209191-20-020278.json,4,True
26,TRC/0001209191-20-024112/0001209191-20-024112.json,4,True
27,VTR/0000740260-22-000089/0000740260-22-000089.json,4,True
28,ADSK/0001209191-20-021012/0001209191-20-021012.json,3,True
29,AMD/0000002488-18-000045/0000002488-18-000045.json,3,True
30,CVLT/0001209191-18-061223/0001209191-18-061223.json,3,True
31,EQH/0001209191-20-017245/0001209191-20-017245.json,3,True
32,HLX/0001209191-20-022554/0001209191-20-022554.json,3,True
33,INTC/0001127602-21-027635/0001127602-21-027635.json,3,True
34,KDP/0001209191-20-018902/0001209191-20-018902.json,3,True
35,LII/0001127602-20-011102/0001127602-20-011102.json,3,True
36,PSN/0000899243-20-008612/0000899243-20-008612.json,3,True
37,SNAP/0001209191-20-020112/0001209191-20-020112.json,3,True
38,TRIP/0001127602-20-009718/0001127602-20-009718.json,3,True
39,CACC/0000885550-20-000030/0000885550-20-000030.json,2,True
40,CAT/0000018230-19-000102/0000018230-19-000102.json,2,True
41,CBT/0001209191-22-040221/0001209191-22-040221.json,2,True
42,FBP/0001209191-20-020889/0001209191-20-020889.json,2,True
43,IDCC/0001209191-20-025667/0001209191-20-025667.json,2,True
44,NBIX/0001209191-22-030998/0001209191-22-030998.json,2,True
45,PSN/0000899243-20-008522/0000899243-20-008522.json,2,True
46,UPBD/0000933036-21-000014/0000933036-21-000014.json,2,True
47,UPBD/0000933036-21-000095/0000933036-21-000095.json,2,True
48,CFG/0000759944-20-000054/0000759944-20-000054.json,1,True
49,HESM/0001209191-20-015600/0001209191-20-015600.json,1,True
50,HOOD/0001783879-22-000098/0001783879-22-000098.json,1,True
51,VICI/0001705696-20-000072/0001705696-20-000072.json,1,True
52,VYX/0001209191-20-025445/0001209191-20-025445.json,1,True
53,WES/0001127602-20-009648/0001127602-20-009648.json,1,True

Example file with differences: TDG/0000919574-20-002399/0000919574-20-002399.json

,field_path,batch4_value,batch8_value
0,date_of_earliest_transaction,03/10/2020,2020-03-10
1,filing_date,03/12/2020,2020-03-12
2,table_i_non_derivative[0].transaction_date,03/11/2020,2020-03-11
3,table_i_non_derivative[10].transaction_date,03/11/2020,2020-03-11
4,table_i_non_derivative[11].transaction_date,03/11/2020,2020-03-11
5,table_i_non_derivative[12].transaction_date,03/11/2020,2020-03-11
6,table_i_non_derivative[13].transaction_date,03/11/2020,2020-03-11
7,table_i_non_derivative[14].transaction_date,03/11/2020,2020-03-11
8,table_i_non_derivative[15].transaction_date,03/11/2020,2020-03-11
9,table_i_non_derivative[16].transaction_date,03/11/2020,2020-03-11
10,table_i_non_derivative[17].transaction_date,03/11/2020,2020-03-11
11,table_i_non_derivative[18].transaction_date,03/11/2020,2020-03-11
12,table_i_non_derivative[19].transaction_date,03/11/2020,2020-03-11
13,table_i_non_derivative[1].transaction_date,03/11/2020,2020-03-11
14,table_i_non_derivative[20].transaction_date,03/11/2020,2020-03-11
15,table_i_non_derivative[21].transaction_date,03/11/2020,2020-03-11
16,table_i_non_derivative[22].transaction_date,03/11/2020,2020-03-11
17,table_i_non_derivative[23].transaction_date,03/11/2020,2020-03-11
18,table_i_non_derivative[24].transaction_date,03/11/2020,2020-03-11
19,table_i_non_derivative[25].transaction_date,03/11/2020,2020-03-11
20,table_i_non_derivative[26].transaction_date,03/11/2020,2020-03-11
21,table_i_non_derivative[27].shares_owned_following_transaction,20301,NaN
22,table_i_non_derivative[28].shares_owned_following_transaction,16765,NaN
23,table_i_non_derivative[29].shares_owned_following_transaction,58683,NaN
24,table_i_non_derivative[2].transaction_date,03/11/2020,2020-03-11
25,table_i_non_derivative[3].transaction_date,03/11/2020,2020-03-11
26,table_i_non_derivative[4].transaction_date,03/11/2020,2020-03-11
27,table_i_non_derivative[5].transaction_date,03/11/2020,2020-03-11
28,table_i_non_derivative[6].transaction_date,03/11/2020,2020-03-11
29,table_i_non_derivative[7].transaction_date,03/11/2020,2020-03-11
30,table_i_non_derivative[8].transaction_date,03/11/2020,2020-03-11
31,table_i_non_derivative[9].transaction_date,03/11/2020,2020-03-11